# Generated by Django 3.1.8 on 2021-04-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_clothes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='Tags',
            new_name='tags',
        ),
    ]
