# Generated by Django 3.1.8 on 2021-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_auto_20210409_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_image_file_path'),
        ),
    ]
