# Generated by Django 3.1.8 on 2021-04-10 07:10

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_auto_20210409_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=clothes.models.clothes_image_file_path),
        ),
    ]
