# Generated by Django 3.1.9 on 2021-05-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0017_auto_20210410_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/%Y/%m/%d'),
        ),
    ]
