# Generated by Django 3.1.9 on 2021-05-07 02:01

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_auto_20210507_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=clothes.models.clothes_image_file_path),
        ),
    ]
